server:
  port: 8081
  servlet:
    context-path: /api

spring:
  datasource:
    #url: jdbc:postgresql://localhost:5433/productdb
    url: jdbc:postgresql://host.docker.internal:5433/productdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

security:
  api-key: 20bcb55b4f24ec60b525f4c55cf20d5e9f66372121991c3a918fd8146e4b4ced

logging:
  level:
    org:
      hibernate:
        SQL: warn
        type:
          descriptor:
            sql:
              BasicBinder: warn
    org.hibernate.orm.connections.pooling: WARN
    com.zaxxer.hikari: WARN
aws:
  access-key: ${AWS_ACCESS_KEY_ID}
  secret-key: ${AWS_SECRET_ACCESS_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_BUCKET_NAME}
    endpoint: ${AWS_ENDPOINT}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
